import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Easing,
  Img,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
} from 'remotion';

export const FPS = 30;
export const SHOTS = {
  brand: {from: 0, duration: 90},
  install: {from: 90, duration: 150},
  panel: {from: 240, duration: 150},
  vision: {from: 390, duration: 120},
  routing: {from: 510, duration: 150},
  workflowTitle: {from: 660, duration: 54},
  workflow: {from: 714, duration: 180},
  deliverables: {from: 894, duration: 111},
  outro: {from: 1005, duration: 150},
} as const;
export const TOTAL = 1155;

type Locale = 'zh' | 'en';
type DemoProps = {locale: Locale; bgm?: boolean};
const CLAMP = {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const;
const EASE = Easing.bezier(0, 0, 0.2, 1);
const LAND = Easing.bezier(0.34, 1.4, 0.44, 1);
const FONT = 'Inter, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif';
const MONO = 'Consolas, "SFMono-Regular", monospace';
const C = {
  ink: '#10131a', soft: '#3e4655', muted: '#6f7888', line: '#dce1e9',
  paper: '#ffffff', wash: '#f5f7fb', blueWash: '#edf3ff', blue: '#356df3',
  blueDark: '#2455cc', green: '#117a61', dark: '#090c13', panel: '#111827',
};

const copy = {
  zh: {
    brandKicker: 'DEEPSEEK HARNESS · 插件组',
    brandLine: '让 DeepSeek 看见，也让合适的模型做合适的事。',
    installCaption: '一行安装。没有第二个控制台，也不重复保存 API Key。',
    panelCaption: '在 Harness 原生侧栏里，选择视觉模型或本地 OCR。',
    panelNote: '视觉读取者',
    visionCaption: '图片先变成可靠观察，再交回主模型继续回答。',
    visionTitle: '视觉观察',
    visionRows: ['识别文字：DeepSee', '版式：竖版发布海报', '主色：蓝色与白色', '结果：已交给主模型'],
    routingCaption: '只启用验证通过的路线；按能力选择模型，而不是盲目轮询。',
    routeHub: '已验证路线',
    routeNodes: [['DeepSeek', '规划 · 文案'], ['Codex', '代码 · 设计'], ['Claude', '分析 · 审查'], ['视觉 / OCR', '观察']],
    title: '一次规划，按能力分工。',
    workflowCaption: '执行轨迹让每个 Agent 的任务、模型和结果都清晰可见。',
    workflowSummary: '发布素材已经准备完成。',
    workflowTask: '制作 DeepSee 发布海报并完成核验',
    workflowRows: [
      ['DeepSeek V4 Flash', '完成中文与英文文案'],
      ['Codex · GPT-5.6', '生成海报与可编辑源文件'],
      ['MiMo V2.5', '读取 PNG 并完成视觉核验'],
      ['DeepSeek', '汇总发布报告'],
    ],
    complete: 'Workflow 完成',
    deliverCaption: '结果不只留在文件夹里：交付物可以直接打开。',
    deliverTitle: '交付结果',
    deliverSub: '由 Workflow 生成 · 可在 Harness 内打开',
    open: '打开',
    finalLine: '让 DeepSeek 看见。保持原来的 Harness。',
    install: '一行安装',
    independent: '独立开源插件 · MIT',
  },
  en: {
    brandKicker: 'DEEPSEEK HARNESS · PLUGIN GROUP',
    brandLine: 'Give DeepSeek sight. Give every task the right model.',
    installCaption: 'One-line install. No second console. No duplicate API keys.',
    panelCaption: 'Choose a vision model or local OCR inside the native Harness sidebar.',
    panelNote: 'VISUAL READER',
    visionCaption: 'Turn an image into a grounded observation, then return it to the main model.',
    visionTitle: 'Visual observation',
    visionRows: ['Text: DeepSee', 'Layout: portrait launch poster', 'Palette: blue and white', 'Result: sent to the main model'],
    routingCaption: 'Enable only verified routes, then select by capability—not by guesswork.',
    routeHub: 'verified routes',
    routeNodes: [['DeepSeek', 'plan · copy'], ['Codex', 'code · design'], ['Claude', 'analysis · review'], ['Vision / OCR', 'observe']],
    title: 'Plan once. Route by strength.',
    workflowCaption: 'The execution trace keeps every agent, model, task, and result visible.',
    workflowSummary: 'Launch assets are ready.',
    workflowTask: 'Create and verify the DeepSee launch poster',
    workflowRows: [
      ['DeepSeek V4 Flash', 'Wrote Chinese and English copy'],
      ['Codex · GPT-5.6', 'Generated poster and editable source'],
      ['MiMo V2.5', 'Read the PNG and verified the layout'],
      ['DeepSeek', 'Compiled the launch report'],
    ],
    complete: 'Workflow complete',
    deliverCaption: 'Results do not disappear into a folder. Open every deliverable directly.',
    deliverTitle: 'Deliverables',
    deliverSub: 'Generated by Workflow · open inside Harness',
    open: 'Open',
    finalLine: 'Add sight. Keep the Harness.',
    install: 'Install in one line',
    independent: 'Independent open-source plugin · MIT',
  },
} as const;

const Caption: React.FC<{text: string; dark?: boolean}> = ({text, dark = false}) => (
  <div style={{position: 'absolute', left: 120, right: 120, bottom: 52, zIndex: 30, display: 'flex', justifyContent: 'center'}}>
    <div style={{maxWidth: 1500, padding: '15px 26px', borderRadius: 18, color: dark ? '#f7f9ff' : C.ink, background: dark ? 'rgba(9,12,19,.78)' : 'rgba(255,255,255,.88)', border: `1px solid ${dark ? 'rgba(255,255,255,.13)' : 'rgba(220,225,233,.92)'}`, boxShadow: '0 12px 42px rgba(16,19,26,.10)', backdropFilter: 'blur(14px)', fontFamily: FONT, fontSize: 58, fontWeight: 700, lineHeight: 1.16, letterSpacing: '-.035em', textAlign: 'center'}}>{text}</div>
  </div>
);

const BrandScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const drawV = interpolate(frame, [0, 10], [100, 0], {...CLAMP, easing: EASE});
  const drawH = interpolate(frame, [8, 20], [100, 0], {...CLAMP, easing: EASE});
  const crossOut = interpolate(frame, [24, 34], [1, 0], CLAMP);
  const out = interpolate(frame, [82, 90], [0, 1], {...CLAMP, easing: Easing.in(Easing.cubic)});
  return (
    <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, opacity: 1 - out}}>
      <div style={{position: 'absolute', width: 980, height: 780, right: -260, top: -360, borderRadius: 999, background: 'radial-gradient(circle, rgba(53,109,243,.16), rgba(255,255,255,0) 70%)'}}/>
      <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center', transform: `translateY(${-38 * out}px) scale(${1 - .08 * out})`}}>
        <svg width="82" height="82" viewBox="0 0 82 82" style={{opacity: crossOut, marginBottom: 34}}>
          <line x1="41" y1="4" x2="41" y2="78" stroke={C.blue} strokeWidth="5" strokeLinecap="round" pathLength="100" strokeDasharray="100" strokeDashoffset={drawV}/>
          <line x1="4" y1="41" x2="78" y2="41" stroke={C.blue} strokeWidth="5" strokeLinecap="round" pathLength="100" strokeDasharray="100" strokeDashoffset={drawH}/>
        </svg>
        <div style={{display: 'flex', fontSize: 154, fontWeight: 780, letterSpacing: '-.065em', lineHeight: 1}}>
          {'DeepSee'.split('').map((ch, i) => {
            const p = interpolate(frame, [12 + i * 4, 28 + i * 4], [0, 1], {...CLAMP, easing: EASE});
            return <span key={`${ch}-${i}`} style={{display: 'inline-block', opacity: p, transform: `scale(${1.55 - .55 * p})`, filter: `blur(${7 * (1 - p)}px)`}}>{ch}</span>;
          })}
        </div>
        <div style={{marginTop: 26, color: C.blueDark, fontFamily: MONO, fontSize: 32, fontWeight: 700, letterSpacing: '.1em'}}>{t.brandKicker}</div>
        <div style={{marginTop: 40, maxWidth: 1320, color: C.soft, fontSize: 58, fontWeight: 650, lineHeight: 1.22, textAlign: 'center', letterSpacing: '-.035em'}}>{t.brandLine}</div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const COMMAND = 'npx --yes github:WUBING2023/deepsee install';
const TerminalScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const chars = Math.min(COMMAND.length, Math.max(0, Math.floor((frame - 12) / 2)));
  const enter = 112;
  const cut = frame >= 120;
  const push = interpolate(frame, [enter, 120], [1, 3.2], {...CLAMP, easing: Easing.in(Easing.cubic)});
  const blur = interpolate(frame, [117, 120], [0, 12], CLAMP);
  const dashScale = interpolate(frame, [120, 128], [1.06, 1], {...CLAMP, easing: Easing.out(Easing.cubic)});
  return (
    <AbsoluteFill style={{background: '#111722', color: '#f7f9fd', fontFamily: FONT, overflow: 'hidden'}}>
      {!cut ? <div style={{width: 1920, height: 1080, transform: `scale(${push})`, transformOrigin: '960px 500px', filter: `blur(${blur}px)`}}>
        <div style={{position: 'absolute', left: 260, top: 210, width: 1400, height: 560, overflow: 'hidden', borderRadius: 28, background: '#151a24', border: '1px solid #30394a', boxShadow: '0 42px 120px rgba(0,0,0,.42)'}}>
          <div style={{height: 82, display: 'flex', alignItems: 'center', gap: 13, padding: '0 28px', borderBottom: '1px solid #30394a', color: '#8e9aae', font: `600 32px ${MONO}`}}>
            {['#657083', '#8490a3', '#a8b4c6'].map((x) => <i key={x} style={{width: 15, height: 15, borderRadius: 99, background: x}}/>)}
            <span style={{marginLeft: 18}}>PowerShell / Terminal</span>
          </div>
          <div style={{padding: '130px 72px', whiteSpace: 'pre', font: `500 42px/1.4 ${MONO}`}}>
            <span style={{color: '#80a5ff'}}>$ </span>{COMMAND.substring(0, chars)}<span style={{display: 'inline-block', width: 23, height: 48, marginLeft: 5, verticalAlign: -8, background: '#9ab7ff', opacity: frame % 12 < 6 ? 1 : 0}}/>
          </div>
        </div>
      </div> : <AbsoluteFill style={{transform: `scale(${dashScale})`}}><Img src={staticFile('textures/deepsee-panel.png')} style={{width: '100%', height: '100%', objectFit: 'cover'}}/></AbsoluteFill>}
      {frame < 108 ? <Caption text={copy[locale].installCaption} dark/> : null}
    </AbsoluteFill>
  );
};

const PanelScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const inP = interpolate(frame, [0, 20], [0, 1], {...CLAMP, easing: EASE});
  const rise = interpolate(frame, [46, 62], [0, 1], {...CLAMP, easing: LAND});
  const reseat = interpolate(frame, [108, 130], [0, 1], {...CLAMP, easing: EASE});
  const lift = rise * (1 - reseat);
  const beam = interpolate(frame, [66, 96], [0, 1], CLAMP);
  return (
    <AbsoluteFill style={{background: C.wash, fontFamily: FONT, overflow: 'hidden'}}>
      <div style={{position: 'absolute', inset: 0, opacity: inP, transform: `perspective(1500px) rotateY(${-7 * (1 - inP)}deg) scale(${.94 + .06 * inP})`}}>
        <Img src={staticFile('textures/deepsee-panel.png')} style={{position: 'absolute', left: 240, top: 60, width: 1440, height: 960, borderRadius: 34, boxShadow: '0 50px 130px rgba(24,35,56,.18)'}}/>
        <div style={{position: 'absolute', inset: 0, background: 'radial-gradient(430px 260px at 31.5% 29%, rgba(255,255,255,.1), rgba(21,30,48,.50) 86%)', opacity: interpolate(frame, [20, 52], [0, .7], CLAMP)}}/>
        <div style={{position: 'absolute', left: 428, top: 320, width: 356, height: 81, borderRadius: 18, backgroundImage: `url(${staticFile('textures/deepsee-panel.png')})`, backgroundSize: '1440px 960px', backgroundPosition: '-188px -260px', transform: `translateY(${-82 * lift}px) translateZ(${120 * lift}px) scale(${1 + .07 * lift})`, boxShadow: `0 ${14 + 38 * lift}px ${30 + 70 * lift}px rgba(31,45,75,${.14 + .18 * lift})`, overflow: 'hidden'}}>
          {beam > 0 && beam < 1 ? <svg width="356" height="81" viewBox="0 0 356 81" style={{position: 'absolute', inset: 0, filter: 'drop-shadow(0 0 8px #356df3)'}}><rect x="2" y="2" width="352" height="77" rx="16" fill="none" stroke="#356df3" strokeWidth="4" pathLength="1" strokeDasharray=".18 1" strokeDashoffset={-beam}/></svg> : null}
        </div>
        <div style={{position: 'absolute', left: 435, top: 218, padding: '14px 22px', borderRadius: 999, color: C.blueDark, background: '#ffffffee', border: `1px solid ${C.line}`, opacity: interpolate(frame, [56, 70, 102, 112], [0, 1, 1, 0], CLAMP), font: `700 32px ${MONO}`, letterSpacing: '.06em'}}>{copy[locale].panelNote}</div>
      </div>
      <Caption text={copy[locale].panelCaption}/>
    </AbsoluteFill>
  );
};

const VisionScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const imageIn = interpolate(frame, [0, 18], [0, 1], {...CLAMP, easing: EASE});
  const scan = interpolate(frame, [22, 65], [0, 1], CLAMP);
  const rowCues = [42, 56, 70, 84];
  return (
    <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
      <div style={{position: 'absolute', width: 760, height: 760, left: -180, top: 130, borderRadius: 999, background: 'radial-gradient(circle, rgba(53,109,243,.13), transparent 68%)'}}/>
      <div style={{position: 'absolute', left: 170, top: 190, width: 560, height: 610, opacity: imageIn, transform: `translateY(${36 * (1 - imageIn)}px) rotate(${-2 + 2 * imageIn}deg)`, borderRadius: 34, overflow: 'hidden', background: 'linear-gradient(155deg,#edf3ff,#fff)', border: `1px solid ${C.line}`, boxShadow: '0 35px 90px rgba(24,35,56,.16)'}}>
        <div style={{position: 'absolute', inset: 34, borderRadius: 25, background: 'linear-gradient(145deg,#356df3,#755cff)', display: 'grid', placeItems: 'center', color: 'white'}}>
          <Img src={staticFile('deepsee-mark.svg')} style={{width: 132, height: 132}}/>
          <div style={{position: 'absolute', left: 42, right: 42, bottom: 55, fontSize: 54, fontWeight: 780, letterSpacing: '-.05em'}}>DeepSee</div>
        </div>
        <div style={{position: 'absolute', left: 0, right: 0, top: `${scan * 100}%`, height: 4, background: '#8facff', boxShadow: '0 0 24px #356df3'}}/>
      </div>
      <div style={{position: 'absolute', left: 820, top: 142, width: 920, height: 730, padding: 40, borderRadius: 32, background: C.wash, border: `1px solid ${C.line}`, boxShadow: '0 30px 80px rgba(24,35,56,.10)'}}>
        <div style={{color: C.blueDark, font: `750 32px ${MONO}`, letterSpacing: '.1em'}}>{t.visionTitle.toUpperCase()}</div>
        <div style={{marginTop: 20, fontSize: 52, fontWeight: 760, letterSpacing: '-.045em'}}>{locale === 'zh' ? '图片读取完成' : 'Image read complete'}</div>
        <div style={{position: 'relative', marginTop: 38, height: 440}}>
          {t.visionRows.map((row, i) => {
            const p = interpolate(frame, [rowCues[i], rowCues[i] + 14], [0, 1], {...CLAMP, easing: LAND});
            return <div key={row} style={{position: 'absolute', left: 0, right: 0, top: i * 104, height: 82, display: 'flex', alignItems: 'center', gap: 18, padding: '0 24px', borderRadius: 18, background: '#fff', border: `1px solid ${C.line}`, opacity: p, transform: `perspective(900px) translateY(${-80 * (1 - p)}px) rotateX(${14 * (1 - p)}deg)`, boxShadow: `0 ${24 * (1 - p)}px ${45 * (1 - p)}px rgba(24,35,56,.18)`}}>
              <span style={{width: 28, height: 28, borderRadius: 99, display: 'grid', placeItems: 'center', color: '#fff', background: C.green, fontSize: 18}}>✓</span>
              <strong style={{fontSize: 36, fontWeight: 650}}>{row}</strong>
            </div>;
          })}
        </div>
      </div>
      <Caption text={t.visionCaption}/>
    </AbsoluteFill>
  );
};

const routePositions = [[70, 80], [610, 80], [70, 500], [610, 500]] as const;
const routePaths = ['M 350 145 C 490 145 480 300 560 350', 'M 650 145 C 520 145 540 300 560 350', 'M 350 565 C 490 565 480 410 560 350', 'M 650 565 C 520 565 540 410 560 350'];
const RoutingScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const flip = interpolate(frame, [12, 47], [0, 1], {...CLAMP, easing: Easing.out(Easing.cubic)});
  const nodes = interpolate(frame, [50, 62], [0, 1], {...CLAMP, easing: LAND});
  const pipes = interpolate(frame, [62, 72], [0, 1], {...CLAMP, easing: EASE});
  const flow = Math.max(0, frame - 72);
  return (
    <AbsoluteFill style={{background: C.dark, color: '#f4f7ff', fontFamily: FONT, overflow: 'hidden'}}>
      <div style={{position: 'absolute', inset: 0, backgroundImage: 'linear-gradient(rgba(255,255,255,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.045) 1px,transparent 1px)', backgroundSize: '54px 54px', opacity: .55}}/>
      <div style={{position: 'absolute', left: 95, top: 150, width: 650}}>
        <div style={{color: '#6f93ff', font: `750 32px ${MONO}`, letterSpacing: '.12em'}}>MODEL DIRECTORY</div>
        <div style={{marginTop: 22, fontSize: 76, fontWeight: 780, lineHeight: 1.03, letterSpacing: '-.055em'}}>{locale === 'zh' ? <>识别路线。<br/><span style={{color: '#8facff'}}>按能力连接。</span></> : <>Verify routes.<br/><span style={{color: '#8facff'}}>Connect by strength.</span></>}</div>
      </div>
      <div style={{position: 'absolute', right: 90, top: 120, width: 1000, height: 730, transform: `perspective(1300px) rotateY(${180 * (1 - flip)}deg)`, transformStyle: 'preserve-3d'}}>
        <svg width="1000" height="700" style={{position: 'absolute', inset: 0, overflow: 'visible'}}>
          <defs><linearGradient id="route-grad" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#356df3"/><stop offset=".55" stopColor="#8facff"/><stop offset="1" stopColor="#68e0b9"/></linearGradient></defs>
          {routePaths.map((d, i) => <g key={d}><path d={d} fill="none" stroke="url(#route-grad)" strokeWidth="6" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - pipes}/>{pipes >= 1 ? <path d={d} fill="none" stroke="#fff" strokeWidth="10" strokeLinecap="round" pathLength="1" strokeDasharray=".035 .12" strokeDashoffset={-(flow * .012 + i * .11)} opacity=".9"/> : null}</g>)}
        </svg>
        {t.routeNodes.map(([name, role], i) => <div key={name} style={{position: 'absolute', left: routePositions[i][0], top: routePositions[i][1], width: 320, height: 142, padding: '18px 24px', borderRadius: 24, border: '1px solid rgba(255,255,255,.13)', background: 'rgba(17,24,39,.96)', opacity: nodes, transform: `translateY(${24 * (1 - nodes)}px) scale(${.9 + .1 * nodes})`, boxShadow: '0 26px 70px rgba(0,0,0,.35)'}}><i style={{display: 'block', width: 10, height: 10, borderRadius: 99, background: '#68e0b9', boxShadow: '0 0 0 8px rgba(104,224,185,.10)'}}/><strong style={{display: 'block', marginTop: 8, fontSize: 32}}>{name}</strong><span style={{display: 'block', marginTop: 3, color: '#9da9bc', font: `500 32px ${MONO}`, whiteSpace: 'nowrap'}}>{role}</span></div>)}
        <div style={{position: 'absolute', left: 410, top: 250, width: 300, height: 210, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', borderRadius: 30, background: 'linear-gradient(155deg,#1b2742,#0f1626)', border: '1px solid rgba(111,147,255,.55)', boxShadow: '0 30px 90px rgba(53,109,243,.20)'}}><Img src={staticFile('deepsee-mark.svg')} style={{width: 62, height: 62}}/><strong style={{marginTop: 8, fontSize: 36}}>DeepSee</strong><span style={{marginTop: 5, color: '#9facbf', font: `500 32px ${MONO}`}}>{t.routeHub}</span></div>
      </div>
      <Caption text={t.routingCaption} dark/>
    </AbsoluteFill>
  );
};

const WorkflowTitleScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const p = interpolate(frame, [5, 23], [0, 1], {...CLAMP, easing: EASE});
  return <AbsoluteFill style={{background: C.dark, color: '#fff', alignItems: 'center', justifyContent: 'center', fontFamily: FONT}}><div style={{fontSize: locale === 'zh' ? 88 : 82, fontWeight: 780, letterSpacing: '-.055em', opacity: p, transform: `translateY(${25 * (1 - p)}px)`, clipPath: `inset(0 ${100 * (1 - p)}% 0 0)`}}>{copy[locale].title}</div><div style={{position: 'absolute', bottom: 260, width: 300, height: 5, borderRadius: 99, background: C.blue, transform: `scaleX(${p})`}}/></AbsoluteFill>;
};

const WorkflowScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const panelIn = interpolate(frame, [0, 18], [0, 1], {...CLAMP, easing: EASE});
  const summary = interpolate(frame, [22, 38], [0, 1], {...CLAMP, easing: EASE});
  const cues = [52, 76, 100, 124];
  const done = interpolate(frame, [144, 158], [0, 1], {...CLAMP, easing: EASE});
  return (
    <AbsoluteFill style={{background: C.dark, color: '#eef2fa', fontFamily: FONT, overflow: 'hidden'}}>
      <div style={{position: 'absolute', inset: 0, background: 'radial-gradient(circle at 50% 35%,rgba(53,109,243,.15),transparent 65%)'}}/>
      <div style={{position: 'absolute', left: 230, top: 70, width: 1460, height: 890, borderRadius: 32, overflow: 'hidden', background: 'linear-gradient(145deg,#171d28,#0e131c)', border: `1px solid rgba(111,147,255,${.18 + .35 * done})`, boxShadow: '0 50px 120px rgba(0,0,0,.45)', opacity: panelIn, transform: `translateY(${18 * (1 - panelIn)}px) scale(${.985 + .015 * panelIn})`}}>
        <div style={{height: 78, display: 'flex', alignItems: 'center', padding: '0 34px', borderBottom: '1px solid rgba(255,255,255,.075)'}}><Img src={staticFile('deepsee-mark.svg')} style={{width: 38, height: 38}}/><strong style={{marginLeft: 14, fontSize: 32}}>Workflow · DeepSee</strong><span style={{marginLeft: 'auto', color: '#8b96a8', font: `500 32px ${MONO}`}}>4 agents · execution trace</span></div>
        <div style={{padding: '30px 42px'}}>
          <div style={{height: 62, display: 'flex', alignItems: 'center', padding: '0 20px', borderRadius: 14, color: '#c2c9d4', background: 'rgba(255,255,255,.045)', fontSize: 32}}>{t.workflowTask}</div>
          <div style={{height: 132, paddingTop: 14, borderBottom: '1px solid rgba(255,255,255,.075)', opacity: summary, transform: `translateY(${12 * (1 - summary)}px)`, clipPath: `inset(0 ${100 * (1 - summary)}% 0 0)`}}><div style={{color: '#8691a2', font: `700 32px ${MONO}`, letterSpacing: '.1em'}}>RESULT SUMMARY</div><div style={{marginTop: 5, color: '#fff', fontSize: 40, fontWeight: 650, letterSpacing: '-.03em'}}>{t.workflowSummary}</div></div>
          <div style={{position: 'relative', marginTop: 24, height: 440}}>{t.workflowRows.map(([agent, action], i) => {
            const p = interpolate(frame, [cues[i], cues[i] + 16], [0, 1], {...CLAMP, easing: EASE});
            const status = interpolate(frame, [cues[i] + 5, cues[i] + 14], [0, 1], {...CLAMP, easing: EASE});
            return <div key={agent} style={{position: 'absolute', left: 0, right: 0, top: i * 102, height: 88, display: 'grid', gridTemplateColumns: '54px 340px 1fr 170px', alignItems: 'center', padding: '0 24px', borderRadius: 16, border: '1px solid rgba(255,255,255,.075)', background: 'rgba(255,255,255,.025)', opacity: p, transform: `translateY(${20 * (1 - p)}px)`, filter: `blur(${5 * (1 - p)}px)`}}><span style={{width: 30, height: 30, borderRadius: 99, display: 'grid', placeItems: 'center', color: '#102016', background: '#79e6b9', opacity: status, transform: `scale(${.72 + .28 * status})`, fontWeight: 900}}>✓</span><strong style={{fontSize: 32}}>{agent}</strong><span style={{color: '#c1c7d1', fontSize: 32}}>{action}</span><span style={{color: status > .7 ? '#9ee8c5' : '#7f8998', font: `600 32px ${MONO}`}}>{status > .7 ? 'DONE' : 'RUNNING'}</span></div>;
          })}</div>
          <div style={{display: 'flex', alignItems: 'center', gap: 13, marginTop: 12, opacity: done, transform: `translateY(${8 * (1 - done)}px)`}}><span style={{width: 31, height: 31, borderRadius: 99, display: 'grid', placeItems: 'center', color: '#102016', background: '#79e6b9', fontWeight: 900}}>✓</span><strong style={{fontSize: 32, color: '#d7f6e7'}}>{t.complete}</strong><span style={{color: '#7f8998', font: `500 32px ${MONO}`}}>poster.png · report.md · review PASS</span></div>
        </div>
      </div>
      <Caption text={t.workflowCaption} dark/>
    </AbsoluteFill>
  );
};

const DeliverablesScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const titleChars = Math.min(t.deliverTitle.length, Math.max(0, Math.floor((frame - 5) / 3)));
  const files = [['deepsee-poster.png', 'PNG · 1200×1600'], ['deepsee-poster.svg', 'SVG · editable source'], ['launch-report.md', 'Markdown · verified report']] as const;
  return <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', left: 210, top: 120, width: 1500, height: 790, padding: '62px 70px', borderRadius: 36, background: C.wash, border: `1px solid ${C.line}`, boxShadow: '0 35px 90px rgba(24,35,56,.11)'}}>
      <div style={{display: 'flex', alignItems: 'flex-start'}}><div><div style={{fontSize: 68, fontWeight: 780, letterSpacing: '-.055em'}}>{t.deliverTitle.slice(0, titleChars)}<span style={{display: 'inline-block', width: 5, height: 65, marginLeft: 8, verticalAlign: -8, background: C.blue, opacity: frame % 12 < 7 ? 1 : 0}}/></div><div style={{marginTop: 12, color: C.muted, fontSize: 32}}>{t.deliverSub}</div></div><div style={{marginLeft: 'auto', padding: '11px 17px', borderRadius: 999, color: C.green, background: '#e7f7f1', font: `700 32px ${MONO}`}}>WORKFLOW · PASS</div></div>
      <div style={{marginTop: 44, display: 'grid', gap: 22}}>{files.map(([name, meta], i) => {const p = interpolate(frame, [30 + i * 14, 46 + i * 14], [0, 1], {...CLAMP, easing: LAND}); return <div key={name} style={{height: 132, display: 'grid', gridTemplateColumns: '70px 1fr 150px', alignItems: 'center', padding: '0 28px', borderRadius: 22, background: '#fff', border: `1px solid ${C.line}`, opacity: p, transform: `perspective(900px) translateY(${-85 * (1 - p)}px) rotateX(${13 * (1 - p)}deg)`, boxShadow: `0 ${24 * (1 - p)}px ${48 * (1 - p)}px rgba(24,35,56,.16)`}}><span style={{position: 'relative', width: 52, height: 52, borderRadius: 14, display: 'grid', placeItems: 'center', background: i === 0 ? C.blue : i === 1 ? '#7655ee' : C.green}}><i style={{width: 23, height: 29, borderRadius: 3, border: '3px solid #fff', opacity: .94}}/><i style={{position: 'absolute', right: 12, top: 11, width: 9, height: 9, borderTop: '3px solid #fff', borderRight: '3px solid #fff', background: 'transparent'}}/></span><div><strong style={{display: 'block', fontSize: 36}}>{name}</strong><span style={{display: 'block', marginTop: 3, color: C.muted, font: `500 32px ${MONO}`}}>{meta}</span></div><span style={{justifySelf: 'end', color: C.blueDark, fontSize: 32, fontWeight: 700}}>{t.open} ↗</span></div>;})}</div>
    </div>
    <Caption text={t.deliverCaption}/>
  </AbsoluteFill>;
};

const OUTRO_CARDS = [
  {x: 210, y: 180, w: 390, h: 180, dx: -500, dy: -160, rot: -5, color: '#edf3ff'},
  {x: 1320, y: 165, w: 380, h: 190, dx: 520, dy: -160, rot: 5, color: '#f5f7fb'},
  {x: 140, y: 700, w: 430, h: 180, dx: -520, dy: 260, rot: 4, color: '#f5f7fb'},
  {x: 1360, y: 690, w: 390, h: 190, dx: 520, dy: 260, rot: -4, color: '#edf3ff'},
] as const;
const OutroScene: React.FC<{locale: Locale}> = ({locale}) => {
  const frame = useCurrentFrame();
  const t = copy[locale];
  const recede = interpolate(frame, [42, 52], [0, 1], CLAMP);
  const stage = interpolate(frame, [40, 52, 65], [0, .55, .28], CLAMP);
  const command = interpolate(frame, [78, 92], [0, 1], {...CLAMP, easing: EASE});
  const dust = Array.from({length: 20}, (_, i) => ({x: (i * 439 + 137) % 1920, y: (i * 613 + 271) % 1080, size: 2 + i % 3, phase: i * .83}));
  return <AbsoluteFill style={{background: C.paper, color: C.ink, fontFamily: FONT, overflow: 'hidden'}}>
    <div style={{position: 'absolute', inset: 0, transform: `perspective(1400px) rotateX(${interpolate(frame, [0, 40], [4, 0], CLAMP)}deg) scale(${interpolate(frame, [0, 40, 150], [1.06, 1, 1.035], CLAMP)})`}}>{OUTRO_CARDS.map((card, i) => {const p = interpolate(frame, [4 + i * 6, 20 + i * 6], [0, 1], {...CLAMP, easing: LAND}); return <div key={i} style={{position: 'absolute', left: card.x, top: card.y, width: card.w, height: card.h, padding: 24, borderRadius: 24, background: card.color, border: `1px solid ${C.line}`, opacity: p * (1 - .15 * recede), transform: `translate(${card.dx * (1 - p)}px,${card.dy * (1 - p)}px) rotate(${card.rot * (2 - p)}deg) scale(${1.1 - .1 * p})`, boxShadow: `0 ${18 + 36 * (1 - p)}px ${38 + 50 * (1 - p)}px rgba(24,35,56,.16)`}}><span style={{color: C.blueDark, font: `750 32px ${MONO}`, letterSpacing: '.08em'}}>{['VISION', 'RUNTIME', 'WORKFLOW', 'DELIVERABLES'][i]}</span><strong style={{display: 'block', marginTop: 12, fontSize: 34}}>{[locale === 'zh' ? '模型或 OCR 读取' : 'Model or OCR reading', locale === 'zh' ? 'Codex · Claude · DeepSeek' : 'Codex · Claude · DeepSeek', locale === 'zh' ? '执行轨迹清晰可见' : 'Visible execution trace', locale === 'zh' ? '结果可以直接打开' : 'Open results directly'][i]}</strong></div>;})}</div>
    <div style={{position: 'absolute', inset: 0, background: `radial-gradient(700px 360px at 50% 45%,rgba(223,233,255,${stage}),transparent 76%)`}}/>
    {dust.map((d, i) => <i key={i} style={{position: 'absolute', left: d.x + Math.sin(frame * .025 + d.phase) * 12, top: ((d.y - frame * (.3 + (i % 5) * .1)) % 1080 + 1080) % 1080, width: d.size, height: d.size, borderRadius: 99, background: C.blue, opacity: .12 + (i % 5) * .035}}/>)}
    <AbsoluteFill style={{alignItems: 'center', justifyContent: 'center'}}><div style={{display: 'flex', fontSize: 148, fontWeight: 790, letterSpacing: '-.065em'}}>{'DeepSee'.split('').map((ch, i) => {const p = interpolate(frame, [42 + i * 3, 54 + i * 3], [0, 1], {...CLAMP, easing: EASE}); return <span key={`${ch}-${i}`} style={{display: 'inline-block', opacity: p, transform: `translateY(${30 * (1 - p)}px) scale(${1.35 - .35 * p})`, filter: `blur(${7 * (1 - p)}px)`}}>{ch}</span>;})}</div><div style={{marginTop: 22, color: C.soft, fontSize: 58, fontWeight: 650, letterSpacing: '-.025em'}}>{t.finalLine}</div><div style={{marginTop: 28, padding: '18px 25px', borderRadius: 16, color: '#f7f9fd', background: '#151a24', border: '1px solid #30394a', opacity: command, transform: `translateY(${18 * (1 - command)}px)`, font: `500 34px ${MONO}`}}><span style={{color: '#83a7ff'}}>$ </span>{COMMAND}</div><div style={{marginTop: 18, color: C.muted, font: `600 32px ${MONO}`, letterSpacing: '.08em', opacity: command}}>{t.independent}</div></AbsoluteFill>
  </AbsoluteFill>;
};

const FlashCut: React.FC<{cut: number; dark?: boolean}> = ({cut, dark = false}) => {
  const frame = useCurrentFrame();
  const d = Math.abs(frame - cut);
  if (d > 5) return null;
  const opacity = 1 - d / 5;
  return <AbsoluteFill style={{zIndex: 80, pointerEvents: 'none', background: dark ? C.dark : '#fff', opacity}}/>;
};

const SFX = [
  {from: SHOTS.brand.from + 12, src: 'transition-soft.mp3', volume: .38, duration: 40},
  {from: SHOTS.brand.from + 78, src: 'whoosh-fast.mp3', volume: .42, duration: 48},
  {from: SHOTS.install.from + 12, src: 'typewriter-digital.mp3', volume: .30, duration: 55},
  {from: SHOTS.install.from + 67, src: 'typewriter-digital.mp3', volume: .25, duration: 45},
  {from: SHOTS.install.from + 112, src: 'click-camera.mp3', volume: .48, duration: 18},
  {from: SHOTS.install.from + 116, src: 'whoosh-powerful.mp3', volume: .45, duration: 55},
  {from: SHOTS.panel.from + 46, src: 'whoosh-powerful.mp3', volume: .48, duration: 55},
  {from: SHOTS.panel.from + 66, src: 'sparkle-touch.mp3', volume: .24, duration: 64},
  {from: SHOTS.panel.from + 122, src: 'transition-snap.mp3', volume: .44, duration: 25},
  {from: SHOTS.vision.from + 18, src: 'transition-soft.mp3', volume: .36, duration: 42},
  {from: SHOTS.routing.from + 12, src: 'whoosh-fast.mp3', volume: .40, duration: 52},
  {from: SHOTS.routing.from + 62, src: 'click-camera.mp3', volume: .42, duration: 18},
  {from: SHOTS.workflowTitle.from, src: 'swoosh-quick.mp3', volume: .42, duration: 28},
  {from: SHOTS.workflow.from + 18, src: 'transition-soft.mp3', volume: .38, duration: 42},
  {from: SHOTS.workflow.from + 144, src: 'click-camera.mp3', volume: .46, duration: 18},
  {from: SHOTS.deliverables.from + 5, src: 'typewriter-digital.mp3', volume: .28, duration: 45},
  {from: SHOTS.deliverables.from + 72, src: 'click-camera.mp3', volume: .42, duration: 18},
  {from: SHOTS.outro.from, src: 'riser-space-intro.mp3', volume: .44, duration: 145},
  {from: SHOTS.outro.from + 42, src: 'impact-deep-whoosh.mp3', volume: .54, duration: 100},
  {from: SHOTS.outro.from + 70, src: 'sparkle-touch.mp3', volume: .27, duration: 70},
] as const;

export const DeepSeeDemo: React.FC<DemoProps> = ({locale, bgm = true}) => {
  const frame = useCurrentFrame();
  const bgmVolume = interpolate(frame, [0, 30, TOTAL - 55, TOTAL], [0, .27, .27, 0], CLAMP);
  return <AbsoluteFill style={{background: C.paper}}>
    {bgm ? <Audio src={staticFile('audio/bgm-house-vibez.mp3')} volume={bgmVolume}/> : null}
    {SFX.map((s, i) => <Sequence key={`${s.src}-${i}`} from={s.from} durationInFrames={s.duration}><Audio src={staticFile(`audio/${s.src}`)} volume={s.volume}/></Sequence>)}
    <Sequence from={SHOTS.brand.from} durationInFrames={SHOTS.brand.duration}><BrandScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.install.from} durationInFrames={SHOTS.install.duration}><TerminalScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.panel.from} durationInFrames={SHOTS.panel.duration}><PanelScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.vision.from} durationInFrames={SHOTS.vision.duration}><VisionScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.routing.from} durationInFrames={SHOTS.routing.duration}><RoutingScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.workflowTitle.from} durationInFrames={SHOTS.workflowTitle.duration}><WorkflowTitleScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.workflow.from} durationInFrames={SHOTS.workflow.duration}><WorkflowScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.deliverables.from} durationInFrames={SHOTS.deliverables.duration}><DeliverablesScene locale={locale}/></Sequence>
    <Sequence from={SHOTS.outro.from} durationInFrames={SHOTS.outro.duration}><OutroScene locale={locale}/></Sequence>
    <FlashCut cut={SHOTS.install.from} dark/>
    <FlashCut cut={SHOTS.panel.from}/>
    <FlashCut cut={SHOTS.vision.from}/>
    <FlashCut cut={SHOTS.routing.from} dark/>
    <FlashCut cut={SHOTS.workflowTitle.from} dark/>
    <FlashCut cut={SHOTS.workflow.from} dark/>
    <FlashCut cut={SHOTS.deliverables.from}/>
    <FlashCut cut={SHOTS.outro.from}/>
  </AbsoluteFill>;
};
